from datetime import datetime

def sample_articles():
    return [
      {"id":"art-reuters-001","source_id":"reuters","title":"Officials announce a regional climate agreement","original_title":"Officials announce a regional climate agreement","url":"https://example.com/reuters/climate-agreement","published_at":"2026-09-24T06:00:00Z","language":"en","body":"Officials from several countries announced a regional climate agreement on Thursday."},
      {"id":"art-xinhua-001","source_id":"xinhuanet","title":"多国发表区域气候合作声明","original_title":"多国发表区域气候合作声明","url":"https://example.com/xinhua/climate-agreement","published_at":"2026-09-24T14:10:00+08:00","language":"zh","body":"多国官员发表区域气候合作声明，表示将继续协商执行安排。"},
      {"id":"art-local-001","source_id":"cna","title":"Local businesses prepare for new trade rules","original_title":"Local businesses prepare for new trade rules","url":"https://example.com/cna/trade-rules","published_at":"2026-09-24T04:00:00Z","language":"en","body":"Businesses in the region are preparing for new trade rules, according to interviews."}
    ]

def sample_events():
    return [{"event_id":"event-climate-2026-09-24","category":"国际/环境","title":"多国宣布区域气候合作安排","summary":"多国官员宣布区域气候合作声明，并表示将继续协商执行安排。当前材料显示协议已被宣布，但具体执行细节仍不完整。","claims":[{"text":"多国官员宣布了区域气候合作声明。","supporting_article_ids":["art-reuters-001","art-xinhua-001"],"evidence":[{"article_id":"art-reuters-001","quote":"Officials from several countries announced a regional climate agreement on Thursday."},{"article_id":"art-xinhua-001","quote":"多国官员发表区域气候合作声明"}],"attribution":"共同可核对","status":"supported"}],"differences":[{"article_ids":["art-reuters-001","art-xinhua-001"],"text":"英文报道强调协议宣布；中文报道强调后续协商，侧重点不同。"}],"uncertainty":"目前不能从取得的公开材料确认具体执行时间表。","sources":[{"name":"Reuters","original_title":"Officials announce a regional climate agreement","translated_title":"官员宣布区域气候合作协议","translated_excerpt":"多国官员于周四宣布一项区域气候合作协议。","published_at":"2026-09-24 14:00（北京时间）","url":"https://example.com/reuters/climate-agreement"},{"name":"新华社","original_title":"多国发表区域气候合作声明","published_at":"2026-09-24 14:10（北京时间）","url":"https://example.com/xinhua/climate-agreement"}]},{"event_id":"event-trade-2026-09-24","category":"经济","title":"企业准备应对新的贸易规则","summary":"区域企业正在准备适应新的贸易规则，报道依据为对企业的采访。","claims":[{"text":"受访企业正在准备应对新的贸易规则。","supporting_article_ids":["art-local-001"],"evidence":[{"article_id":"art-local-001","quote":"Businesses in the region are preparing for new trade rules, according to interviews."}],"attribution":"CNA 引述受访者","status":"single_source"}],"differences":[],"uncertainty":"仅有一个来源，规则具体内容和影响范围尚未独立核对。","sources":[{"name":"CNA","original_title":"Local businesses prepare for new trade rules","translated_title":"当地企业准备应对新的贸易规则","translated_excerpt":"据采访，当地企业正在准备应对新的贸易规则。","published_at":"2026-09-24 12:00（北京时间）","url":"https://example.com/cna/trade-rules"}]}]
